version: '3'

services:
  app:
    container_name: api
    image: keycloak/api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./src/:/code/app/

  keycloak:
    container_name: identity
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8085:8080
    command: ["start-dev"]
    

  # postgres:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_DB: testkeycloakdb
  #     POSTGRES_USER: testkeycloakuser
  #     POSTGRES_PASSWORD: testkeycloakpassword

  # keycloak:
  #   image: jboss/keycloak:16.1.1
  #   volumes:
  #     - ./realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
  #   command:
  #     - "-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
  #   environment:
  #     DB_VENDOR: POSTGRES
  #     DB_ADDR: postgres
  #     DB_DATABASE: testkeycloakdb
  #     DB_USER: testkeycloakuser
  #     DB_SCHEMA: public
  #     DB_PASSWORD: testkeycloakpassword
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: admin
  #     PROXY_ADDRESS_FORWARDING: "true"
  #     KEYCLOAK_LOGLEVEL: DEBUG
  #   ports:
  #     - '8085:8080'
  #   depends_on:
  #     - postgres
